package:
  name: shigatyper
  version: 1.0.0a

source:
  git_url: https://github.com/CFSAN-Biostatistics/shigatyper.git

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python
  number: 3

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - samtools >=1.9
    - bcftools >=1.9
    - minimap2 >=2.16
    - pandas >=0.24.2

about:
  home: https://github.com/CFSAN-Biostatistics/shigatyper
  license: Public Domain
  license_family: Public Domain
  summary: Typing tool for Shigella spp. from WGS Illumina sequencing
