{% set name = "SeqSero2S" %}
{% set version = "1.1.3" %}
{% set release = "81053cdd4ea1811c49171904638ae4316f058282" %}
{% set sha256 = "5dc285ad8dfb36cd6f203886dacedce832fbdaa0459594fbeb9af1118d8f7f01" %}

package:
  name: '{{ name | lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/LSTUGA/SeqSero2S/archive/{{ release }}.zip
  sha256: '{{ sha256 }}'

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  run_exports:
    - {{ pin_subpackage('seqsero2s', max_pin="x.x") }}

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - blast >=2.2.28
    - biopython >=1.85
    - samtools >=1.8
    - bedtools =2.17.0
    - sra-tools >=2.8.0
    - spades >=3.9.0
    - salmid >=0.1.23
    - bwa >=0.7.12
    - seqtk >=1.3
    - stringmlst >=0.6.3
    - mlst >=2.21.1
test:
  commands:
    - SeqSero2S.py -h
    - blastn -help
    - SalmID.py -h

about:
  home: https://github.com/LSTUGA/{{ name }}
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: 'LICENSE'
  summary: Simplified Salmonella serotype prediction from genome sequencing data
  dev_url: https://github.com/LSTUGA/{{ name }}

extra:
  recipe-maintainers:
    - LSTUGA
    - crashfrog
  identifiers:
    - doi:10.1128/aem.02600-24
